In [1]:
import pandas as pd
import numpy as np

In [2]:
books = pd.read_csv("books.csv")
ratings = pd.read_csv("ratings.csv")
book_tags = pd.read_csv("book_tags.csv")
tags = pd.read_csv("tags.csv")
to_read = pd.read_csv("to_read.csv")

In [3]:
books.head()

,id,book_id,best_book_id,work_id,books_count,isbn,isbn13,authors,original_publication_year,original_title,...,ratings_count,work_ratings_count,work_text_reviews_count,ratings_1,ratings_2,ratings_3,ratings_4,ratings_5,image_url,small_image_url
0,1,2767052,2767052,2792775,272,439023483,9.780439e+12,Suzanne Collins,2008.0,The Hunger Games,...,4780653,4942365,155254,66715,127936,560092,1481305,2706317,https://images.gr-assets.com/books/1447303603m...,https://images.gr-assets.com/books/1447303603s...
1,2,3,3,4640799,491,439554934,9.780440e+12,"J.K. Rowling, Mary GrandPré",1997.0,Harry Potter and the Philosopher's Stone,...,4602479,4800065,75867,75504,101676,455024,1156318,3011543,https://images.gr-assets.com/books/1474154022m...,https://images.gr-assets.com/books/1474154022s...
2,3,41865,41865,3212258,226,316015849,9.780316e+12,Stephenie Meyer,2005.0,Twilight,...,3866839,3916824,95009,456191,436802,793319,875073,1355439,https://images.gr-assets.com/books/1361039443m...,https://images.gr-assets.com/books/1361039443s...
3,4,2657,2657,3275794,487,61120081,9.780061e+12,Harper Lee,1960.0,To Kill a Mockingbird,...,3198671,3340896,72586,60427,117415,446835,1001952,1714267,https://images.gr-assets.com/books/1361975680m...,https://images.gr-assets.com/books/1361975680s...
4,5,4671,4671,245494,1356,743273567,9.780743e+12,F. Scott Fitzgerald,1925.0,The Great Gatsby,...,2683664,2773745,51992,86236,197621,606158,936012,947718,https://images.gr-assets.com/books/1490528560m...,https://images.gr-assets.com/books/1490528560s...

In [4]:
ratings.head()

   book_id  user_id  rating
0        1      314       5
1        1      439       3
2        1      588       5
3        1     1169       4
4        1     1185       4

In [5]:
book_tags.head()

   goodreads_book_id  tag_id   count
0                  1   30574  167697
1                  1   11305   37174
2                  1   11557   34173
3                  1    8717   12986
4                  1   33114   12716

In [6]:
tags.head()

   tag_id tag_name
0       0        -
1       1     --1-
2       2    --10-
3       3    --12-
4       4   --122-

In [7]:
to_read.head()

   user_id  book_id
0        1      112
1        1      235
2        1      533
3        1     1198
4        1     1874

In [8]:
print("Books:", books.shape)
print("Ratings:", ratings.shape)
print("Book Tags:", book_tags.shape)
print("Tags:", tags.shape)
print("To Read:", to_read.shape)

Books: (10000, 23)
Ratings: (981756, 3)
Book Tags: (999912, 3)
Tags: (34252, 2)
To Read: (912705, 2)

In [9]:
books.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 23 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   id                         10000 non-null  int64
 1   book_id                    10000 non-null  int64
 2   best_book_id               10000 non-null  int64
 3   work_id                    10000 non-null  int64
 4   books_count                10000 non-null  int64
 5   isbn                       9300 non-null   object
 6   isbn13                     9415 non-null   float64
 7   authors                    10000 non-null  object
 8   original_publication_year  9979 non-null   float64
 9   original_title             9415 non-null   object
 10  title                      10000 non-null  object
 11  language_code              8916 non-null   object
 12  average_rating             10000 non-null  float64
 13  ratings_count              10000 non-null  int64
 14  work_ratings_count         10000 non-null  int64
 15  work_text_reviews_count    10000 non-null  int64
 16  ratings_1                  10000 non-null  int64
 17  ratings_2                  10000 non-null  int64
 18  ratings_3                  10000 non-null  int64
 19  ratings_4                  10000 non-null  int64
 20  ratings_5                  10000 non-null  int64
 21  image_url                  10000 non-null  object
 22  small_image_url            10000 non-null  object
dtypes: float64(3), int64(13), object(7)
memory usage: 1.8+ MB

In [10]:
books.isnull().sum()

id                              0
book_id                         0
best_book_id                    0
work_id                         0
books_count                     0
isbn                          700
isbn13                        585
authors                         0
original_publication_year      21
original_title                585
title                           0
language_code                1084
average_rating                  0
ratings_count                   0
work_ratings_count              0
work_text_reviews_count         0
ratings_1                       0
ratings_2                       0
ratings_3                       0
ratings_4                       0
ratings_5                       0
image_url                       0
small_image_url                 0
dtype: int64

In [11]:
books.duplicated().sum()

np.int64(0)

In [12]:
books = books.drop_duplicates()

In [13]:
books.columns

Index(['id', 'book_id', 'best_book_id', 'work_id', 'books_count', 'isbn',
       'isbn13', 'authors', 'original_publication_year', 'original_title',
       'title', 'language_code', 'average_rating', 'ratings_count',
       'work_ratings_count', 'work_text_reviews_count', 'ratings_1',
       'ratings_2', 'ratings_3', 'ratings_4', 'ratings_5', 'image_url',
       'small_image_url'],
      dtype='object')

In [14]:
books.describe()

,id,book_id,best_book_id,work_id,books_count,isbn13,original_publication_year,average_rating,ratings_count,work_ratings_count,work_text_reviews_count,ratings_1,ratings_2,ratings_3,ratings_4,ratings_5
count,10000.00000,1.000000e+04,1.000000e+04,1.000000e+04,10000.000000,9.415000e+03,9979.000000,10000.000000,1.000000e+04,1.000000e+04,10000.000000,10000.000000,10000.000000,10000.000000,1.000000e+04,1.000000e+04
mean,5000.50000,5.264697e+06,5.471214e+06,8.646183e+06,75.712700,9.755044e+12,1981.987674,4.002191,5.400124e+04,5.968732e+04,2919.955300,1345.040600,3110.885000,11475.893800,1.996570e+04,2.378981e+04
std,2886.89568,7.575462e+06,7.827330e+06,1.175106e+07,170.470728,4.428619e+11,152.576665,0.254427,1.573700e+05,1.678038e+05,6124.378132,6635.626263,9717.123578,28546.449183,5.144736e+04,7.976889e+04
min,1.00000,1.000000e+00,1.000000e+00,8.700000e+01,1.000000,1.951703e+08,-1750.000000,2.470000,2.716000e+03,5.510000e+03,3.000000,11.000000,30.000000,323.000000,7.500000e+02,7.540000e+02
25%,2500.75000,4.627575e+04,4.791175e+04,1.008841e+06,23.000000,9.780316e+12,1990.000000,3.850000,1.356875e+04,1.543875e+04,694.000000,196.000000,656.000000,3112.000000,5.405750e+03,5.334000e+03
50%,5000.50000,3.949655e+05,4.251235e+05,2.719524e+06,40.000000,9.780452e+12,2004.000000,4.020000,2.115550e+04,2.383250e+04,1402.000000,391.000000,1163.000000,4894.000000,8.269500e+03,8.836000e+03
75%,7500.25000,9.382225e+06,9.636112e+06,1.451775e+07,67.000000,9.780831e+12,2011.000000,4.180000,4.105350e+04,4.591500e+04,2744.250000,885.000000,2353.250000,9287.000000,1.602350e+04,1.730450e+04
max,10000.00000,3.328864e+07,3.553423e+07,5.639960e+07,3455.000000,9.790008e+12,2017.000000,4.820000,4.780653e+06,4.942365e+06,155254.000000,456191.000000,436802.000000,793319.000000,1.481305e+06,3.011543e+06

In [15]:
books.isnull().sum()

id                              0
book_id                         0
best_book_id                    0
work_id                         0
books_count                     0
isbn                          700
isbn13                        585
authors                         0
original_publication_year      21
original_title                585
title                           0
language_code                1084
average_rating                  0
ratings_count                   0
work_ratings_count              0
work_text_reviews_count         0
ratings_1                       0
ratings_2                       0
ratings_3                       0
ratings_4                       0
ratings_5                       0
image_url                       0
small_image_url                 0
dtype: int64

In [16]:
books = books[
    [
        "book_id",
        "title",
        "authors",
        "average_rating",
        "ratings_count",
        "original_publication_year",
        "image_url"
    ]
]

In [17]:
books.head()

,book_id,title,authors,average_rating,ratings_count,original_publication_year,image_url
0,2767052,"The Hunger Games (The Hunger Games, #1)",Suzanne Collins,4.34,4780653,2008.0,https://images.gr-assets.com/books/1447303603m...
1,3,Harry Potter and the Sorcerer's Stone (Harry P...,"J.K. Rowling, Mary GrandPré",4.44,4602479,1997.0,https://images.gr-assets.com/books/1474154022m...
2,41865,"Twilight (Twilight, #1)",Stephenie Meyer,3.57,3866839,2005.0,https://images.gr-assets.com/books/1361039443m...
3,2657,To Kill a Mockingbird,Harper Lee,4.25,3198671,1960.0,https://images.gr-assets.com/books/1361975680m...
4,4671,The Great Gatsby,F. Scott Fitzgerald,3.89,2683664,1925.0,https://images.gr-assets.com/books/1490528560m...

In [18]:
books.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 7 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   book_id                    10000 non-null  int64
 1   title                      10000 non-null  object
 2   authors                    10000 non-null  object
 3   average_rating             10000 non-null  float64
 4   ratings_count              10000 non-null  int64
 5   original_publication_year  9979 non-null   float64
 6   image_url                  10000 non-null  object
dtypes: float64(2), int64(2), object(3)
memory usage: 547.0+ KB

In [19]:
books.shape

(10000, 7)

In [20]:
books.isnull().sum()

book_id                       0
title                         0
authors                       0
average_rating                0
ratings_count                 0
original_publication_year    21
image_url                     0
dtype: int64

In [21]:
books = books.dropna()

In [22]:
books.isnull().sum()

book_id                      0
title                        0
authors                      0
average_rating               0
ratings_count                0
original_publication_year    0
image_url                    0
dtype: int64

In [23]:
books["original_publication_year"] = books["original_publication_year"].astype(int)

In [24]:
books.dtypes

book_id                        int64
title                         object
authors                       object
average_rating               float64
ratings_count                  int64
original_publication_year      int64
image_url                     object
dtype: object

In [25]:
books.rename(columns={
    "book_id": "Book_ID",
    "title": "Title",
    "authors": "Author",
    "average_rating": "Rating",
    "ratings_count": "Ratings_Count",
    "original_publication_year": "Year",
    "image_url": "Image_URL"
}, inplace=True)

In [26]:
books.head()

,Book_ID,Title,Author,Rating,Ratings_Count,Year,Image_URL
0,2767052,"The Hunger Games (The Hunger Games, #1)",Suzanne Collins,4.34,4780653,2008,https://images.gr-assets.com/books/1447303603m...
1,3,Harry Potter and the Sorcerer's Stone (Harry P...,"J.K. Rowling, Mary GrandPré",4.44,4602479,1997,https://images.gr-assets.com/books/1474154022m...
2,41865,"Twilight (Twilight, #1)",Stephenie Meyer,3.57,3866839,2005,https://images.gr-assets.com/books/1361039443m...
3,2657,To Kill a Mockingbird,Harper Lee,4.25,3198671,1960,https://images.gr-assets.com/books/1361975680m...
4,4671,The Great Gatsby,F. Scott Fitzgerald,3.89,2683664,1925,https://images.gr-assets.com/books/1490528560m...

In [27]:
books.to_csv("books_cleaned.csv", index=False)

In [28]:
book_tags.head()

   goodreads_book_id  tag_id   count
0                  1   30574  167697
1                  1   11305   37174
2                  1   11557   34173
3                  1    8717   12986
4                  1   33114   12716

In [29]:
tags.head()

   tag_id tag_name
0       0        -
1       1     --1-
2       2    --10-
3       3    --12-
4       4   --122-

In [30]:
book_tags = book_tags.merge(tags, on="tag_id", how="left")

In [31]:
book_tags.head()

   goodreads_book_id  tag_id   count           tag_name
0                  1   30574  167697            to-read
1                  1   11305   37174            fantasy
2                  1   11557   34173          favorites
3                  1    8717   12986  currently-reading
4                  1   33114   12716        young-adult

In [32]:
book_tags = book_tags.sort_values(
    "count",
    ascending=False
)

In [33]:
book_tags = book_tags.drop_duplicates(
    subset="goodreads_book_id"
)

In [34]:
book_tags = book_tags[
    [
        "goodreads_book_id",
        "tag_name"
    ]
]

In [35]:
book_tags.head()

        goodreads_book_id tag_name
8400                  865  to-read
614494            2429135  to-read
911994           18143977  to-read
200                     3  to-read
167200              24280  to-read

In [36]:
book_tags.rename(
    columns={
        "goodreads_book_id": "Book_ID",
        "tag_name": "Genre"
    },
    inplace=True
)

In [37]:
book_tags.head()

         Book_ID    Genre
8400         865  to-read
614494   2429135  to-read
911994  18143977  to-read
200            3  to-read
167200     24280  to-read

In [38]:
genre_mapping = {

    # Fantasy
    "fantasy": "Fantasy",
    "magic": "Fantasy",
    "dragons": "Fantasy",
    "wizard": "Fantasy",
    "epic-fantasy": "Fantasy",
    "urban-fantasy": "Fantasy",

    # Romance
    "romance": "Romance",
    "love": "Romance",
    "chick-lit": "Romance",
    "contemporary-romance": "Romance",

    # Mystery
    "mystery": "Mystery",
    "detective": "Mystery",
    "crime": "Mystery",
    "murder": "Mystery",

    # Thriller
    "thriller": "Thriller",
    "suspense": "Thriller",

    # Horror
    "horror": "Horror",
    "paranormal": "Horror",
    "ghosts": "Horror",
    "vampires": "Horror",

    # Science Fiction
    "science-fiction": "Science Fiction",
    "sci-fi": "Science Fiction",
    "dystopia": "Science Fiction",
    "post-apocalyptic": "Science Fiction",

    # Historical
    "historical-fiction": "Historical",
    "history": "Historical",
    "historical": "Historical",

    # Biography
    "biography": "Biography",
    "memoir": "Biography",
    "autobiography": "Biography",

    # Young Adult
    "young-adult": "Young Adult",
    "ya": "Young Adult",

    # Classics
    "classics": "Classics",
    "classic": "Classics",

    # Self Help
    "self-help": "Self Help",
    "personal-development": "Self Help",

    # Business
    "business": "Business",
    "finance": "Business",
    "economics": "Business",

    # Programming
    "programming": "Programming",
    "computer-science": "Programming"
}

In [39]:
book_tags["Genre"] = book_tags["Genre"].str.lower()

book_tags["Genre"] = book_tags["Genre"].map(genre_mapping)

In [40]:
book_tags = book_tags.dropna()

In [41]:
book_tags.head()

        Book_ID     Genre
50700      5907   Fantasy
127600    15881   Fantasy
400           6   Fantasy
15200      1885  Classics
35000      4671  Classics

In [42]:
books = books.merge(
    book_tags,
    on="Book_ID",
    how="left"
)

In [43]:
books.head()

,Book_ID,Title,Author,Rating,Ratings_Count,Year,Image_URL,Genre
0,2767052,"The Hunger Games (The Hunger Games, #1)",Suzanne Collins,4.34,4780653,2008,https://images.gr-assets.com/books/1447303603m...,NaN
1,3,Harry Potter and the Sorcerer's Stone (Harry P...,"J.K. Rowling, Mary GrandPré",4.44,4602479,1997,https://images.gr-assets.com/books/1474154022m...,NaN
2,41865,"Twilight (Twilight, #1)",Stephenie Meyer,3.57,3866839,2005,https://images.gr-assets.com/books/1361039443m...,Young Adult
3,2657,To Kill a Mockingbird,Harper Lee,4.25,3198671,1960,https://images.gr-assets.com/books/1361975680m...,Classics
4,4671,The Great Gatsby,F. Scott Fitzgerald,3.89,2683664,1925,https://images.gr-assets.com/books/1490528560m...,Classics

In [44]:
books = books.dropna(subset=["Genre"])

In [45]:
books["Genre"].value_counts()

Genre
Fantasy            137
Classics            98
Mystery             69
Young Adult         46
Romance             44
Historical          40
Horror              36
Science Fiction     32
Biography            5
Thriller             5
Business             2
Name: count, dtype: int64

In [46]:
books.to_csv("clean_books.csv", index=False)

In [47]:
books["Genre"].value_counts()

Genre
Fantasy            137
Classics            98
Mystery             69
Young Adult         46
Romance             44
Historical          40
Horror              36
Science Fiction     32
Biography            5
Thriller             5
Business             2
Name: count, dtype: int64